
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 11 04:57:03 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 22;
  public static final int READ = 9;
  public static final int OVER = 23;
  public static final int LT = 15;
  public static final int ELSE = 4;
  public static final int PLUS = 20;
  public static final int RPAREN = 25;
  public static final int THEN = 3;
  public static final int SEMI = 26;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int LPAREN = 24;
  public static final int GT = 16;
  public static final int LE = 18;
  public static final int WRITE = 10;
  public static final int ID = 11;
  public static final int NUM = 12;
  public static final int EOF = 0;
  public static final int MINUS = 21;
  public static final int GE = 17;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 13;
  public static final int EQ = 14;
  public static final int FOR = 8;
  public static final int NEQ = 19;
  public static final int REPEAT = 6;
}

