
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 24 07:07:19 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 35;
  public static final int GE = 29;
  public static final int SEMI = 38;
  public static final int LPAREN = 36;
  public static final int REPEAT = 16;
  public static final int LCORCH = 18;
  public static final int INT = 4;
  public static final int FOR = 20;
  public static final int MINUS = 33;
  public static final int WRITE = 22;
  public static final int RPAREN = 37;
  public static final int RCORCH = 19;
  public static final int AND = 8;
  public static final int LT = 27;
  public static final int OR = 9;
  public static final int BOOL = 2;
  public static final int BEGIN = 7;
  public static final int UNTIL = 17;
  public static final int NUM = 24;
  public static final int PLUS = 32;
  public static final int ASSIGN = 25;
  public static final int IF = 12;
  public static final int ID = 23;
  public static final int LE = 30;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int NEQ = 31;
  public static final int VOID = 3;
  public static final int EQ = 26;
  public static final int TIMES = 34;
  public static final int ELSE = 14;
  public static final int READ = 21;
  public static final int THEN = 13;
  public static final int END = 15;
  public static final int FALSE = 6;
  public static final int GT = 28;
}

